### ISSUE TITLE
[1.12] Crash on load

### ISSUE THREAD

**Issue by Symbai** [KewaiiGamer/MultiTools#1]
Using Multitools-1.1.1-1.12.jar
And Forge: 14.21.1.2396

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Multi Tools (multitools)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/registry/IForgeRegistryEntry
	at info.kewaiigamer.multitools.config.ToolsConfig.initConfig(ToolsConfig.java:25)
	at info.kewaiigamer.multitools.proxy.CommonProxy.preInit(CommonProxy.java:12)
	at info.kewaiigamer.multitools.proxy.ClientProxy.preInit(ClientProxy.java:14)
	at info.kewaiigamer.multitools.Main.preInit(Main.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:628)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)

**Comment by KewaiiGamer** [comment]
Issue has been fixed on 2.0.0
